### ISSUE TITLE
Steam Snap Freezes and Becomes Unresponsive

### ISSUE THREAD

**Issue by Swift8641** [canonical/steam-snap#266] opened 2023-06-20 21:18 UTC
**Describe the bug**

**To Reproduce**

1. Download and install Steam Snap
2. Bypass the "Waiting for Network Bug" by enabling Bluetooth
3. Log in and verify your steam account using the two factor code emailed to you
4. Observe that the Steam snap freezes and becomes unresponsive 

**Expected behavior**

Steam loads normally.

**Environment**

`snap run steam.report`

```
chase@chase-System-Product-Name:~$ snap run steam report
Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
steam.sh[62127]: Running Steam on ubuntu 22.04 64-bit
steam.sh[62127]: STEAM_RUNTIME is enabled automatically
setup.sh[62248]: Steam runtime environment up-to-date!
steam.sh[62127]: Steam client's requirements are satisfied
[2023-06-20 17:21:50] Startup - updater built Jun 16 2023 01:41:16
[2023-06-20 17:21:50] Startup - Steam Client launched with: '/home/chase/snap/steam/common/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox' 'report'
06/20 17:21:50 Init: Installing breakpad exception handler for appid(steam)/version(1686880776)/tid(62294)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-06-20 17:21:51] Loading cached metrics from disk (/home/chase/snap/steam/common/.local/share/Steam/package/steam_client_metrics.bin)
[2023-06-20 17:21:51] Using the following download hosts for Public, Realm steamglobal
[2023-06-20 17:21:51] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-06-20 17:21:51] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-06-20 17:21:51] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-06-20 17:21:51] Checking for update on startup
[2023-06-20 17:21:51] Checking for available updates...
[2023-06-20 17:21:51] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12
[2023-06-20 17:21:51] Manifest download: send request
[2023-06-20 17:21:51] Manifest download: waiting for download to finish
[2023-06-20 17:21:51] Manifest download: finished
[2023-06-20 17:21:51] Download skipped: /steam_client_ubuntu12 version 1686880776, installed version 1686880776, existing pending version 0
[2023-06-20 17:21:51] Nothing to do
[2023-06-20 17:21:51] Verifying installation...
[2023-06-20 17:21:51] Performing checksum verification of executable files
[2023-06-20 17:21:51] Verification complete

(process:62294): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf6ab0370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf6aaecc0
GetWin32Stats: display was not open yet, good
Loaded SDL version 3.0.0-1735-g2e465ae31
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[62423]: Runtime for steamwebhelper: defaulting to /home/chase/snap/steam/common/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
/home/chase/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 53: /proc/sys/kernel/unprivileged_userns_clone: Permission denied
/home/chase/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 60: /proc/sys/user/max_user_namespaces: Permission denied
steamwebhelper.sh[62423]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[62423]: CEF sandbox already disabled
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13CAppInfoCacheReadFromDiskThread took 18 milliseconds to initialize
Failed to init SteamVR because it isn't installed
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13
(steam:62294): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
local (potentially out of sync) copy of roaming config loaded - 164 bytes.
BRefreshApplicationsInLibrary 1: 0ms
roaming config store loaded successfully - 164 bytes.
migrating temporary roaming config store

(steam:62294): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Italic.ttf LOCK_SH failed. errno = 13Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
System startup time: 1.65 seconds

(steam:62294): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
BuildCompleteAppOverviewChange: 183 apps
RegisterForAppOverview 1: 2ms
RegisterForAppOverview 2: 2ms


```

**Logs**
`
steam snap`
```
Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
steam.sh[59611]: Running Steam on ubuntu 22.04 64-bit
steam.sh[59611]: STEAM_RUNTIME is enabled automatically
setup.sh[59733]: Steam runtime environment up-to-date!
steam.sh[59611]: Steam client's requirements are satisfied
[2023-06-20 17:09:21] Startup - updater built Jun 16 2023 01:41:16
[2023-06-20 17:09:21] Startup - Steam Client launched with: '/home/chase/snap/steam/common/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox' 'snap'
06/20 17:09:21 Init: Installing breakpad exception handler for appid(steam)/version(1686880776)/tid(59779)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-06-20 17:09:21] Loading cached metrics from disk (/home/chase/snap/steam/common/.local/share/Steam/package/steam_client_metrics.bin)
[2023-06-20 17:09:21] Using the following download hosts for Public, Realm steamglobal
[2023-06-20 17:09:21] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-06-20 17:09:21] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-06-20 17:09:21] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-06-20 17:09:21] Checking for update on startup
[2023-06-20 17:09:21] Checking for available updates...
[2023-06-20 17:09:21] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12
[2023-06-20 17:09:21] Manifest download: send request
[2023-06-20 17:09:21] Manifest download: waiting for download to finish
[2023-06-20 17:09:21] Manifest download: finished
[2023-06-20 17:09:21] Download skipped: /steam_client_ubuntu12 version 1686880776, installed version 1686880776, existing pending version 0
[2023-06-20 17:09:21] Nothing to do
[2023-06-20 17:09:21] Verifying installation...
[2023-06-20 17:09:21] Performing checksum verification of executable files
[2023-06-20 17:09:21] Verification complete

(process:59779): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf6b48370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf6b46cc0
GetWin32Stats: display was not open yet, good
Loaded SDL version 3.0.0-1735-g2e465ae31
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[59907]: Runtime for steamwebhelper: defaulting to /home/chase/snap/steam/common/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
/home/chase/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 53: /proc/sys/kernel/unprivileged_userns_clone: Permission denied
/home/chase/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 60: /proc/sys/user/max_user_namespaces: Permission denied
steamwebhelper.sh[59907]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[59907]: CEF sandbox already disabled
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13CAppInfoCacheReadFromDiskThread took 17 milliseconds to initialize
Failed to init SteamVR because it isn't installed
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13
(steam:59779): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
local (potentially out of sync) copy of roaming config loaded - 164 bytes.
roaming config store loaded successfully - 164 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 0ms

(steam:59779): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Italic.ttf LOCK_SH failed. errno = 13Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
System startup time: 1.95 seconds

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:59779): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
BuildCompleteAppOverviewChange: 183 apps
RegisterForAppOverview 1: 2ms
RegisterForAppOverview 2: 3ms

```

**Comment by Swift8641** [comment] 2023-06-24 17:24
The only way to use the snap currently is to use the terminal command `steam -vgui`.

**Comment by ashuntu** [comment] 2023-10-19 21:34
Is this still an issue? I'm not sure if it's a problem specifically with the Snap, and I'm unable to reproduce it.

I've added that workaround and the `--reset` suggestion from the thread you linked to the [wiki](https://github.com/canonical/steam-snap/wiki/Troubleshooting#steam-run-options) in case it comes up again.

**Comment by Swift8641** [comment] 2023-10-20 21:58
I will have to test it. I found a work around by opening it with Lutris. I will update you after reinstalling.

**Comment by Swift8641** [comment] 2023-11-09 20:07
I haven't reinstalled it yet so I can't confirm it was fixed. I can tell you that starting it through lutris seems to be the only stable way to use the snap so far.

**Comment by ashuntu** [comment] 2024-08-06 21:23
I'm going to close this for now since there has been no progress. Feel free to reopen if its still an issue.

**Closed by ashuntu** 2024-08-06 21:23 UTC
Labels: type/bug, awaiting-confirmation, client-specific
