### ISSUE TITLE
Steam will fail if launched via created shortcut (underlying error appears to be Failed to connect to websocket)

### ISSUE THREAD

**Issue by free2create** [canonical/steam-snap#384] opened 2024-05-24 20:02 UTC
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

From a clean/new ubuntu 24.04 install, snap snapshots disabled and no existing snapshots.

If I launch steam via the snap app store :
![image](https://github.com/canonical/steam-snap/assets/266067/1cf60203-016a-40c2-9127-036d720e1e5b)

or the command line as a non privileged user:
![image](https://github.com/canonical/steam-snap/assets/266067/840a8961-0591-4079-8b7a-593127d9821e)

The steam landing page will be displayed:
![image](https://github.com/canonical/steam-snap/assets/266067/2003310c-694e-4e72-bc4c-175309d1108d)

There are errors displayed such as `flock`(LOCK_SH) errors and GLib-GIO-CRITICAL but these don't seem to impact the stability of steam or the one game I have tried.

These logs are in the 

[successful-launch.zip](https://github.com/canonical/steam-snap/files/15439143/successful-launch.zip) attachment

**However**,  if steam is launched using the created shortcut:

![image](https://github.com/canonical/steam-snap/assets/266067/d8b277f5-8a2e-4cc1-987c-fdac28270122)

The quick launcher will be displayed:
![image](https://github.com/canonical/steam-snap/assets/266067/6580e06d-1bbd-4b47-95c3-c554b1c7c978)

However, the Landing page screen fails to be displayed , and if you watch the pinned apps you can observe the landing page icon appearing then disappearing.

In the _console_log.txt_ in the [failed-launch.zip](https://github.com/canonical/steam-snap/files/15439324/failed-launch.zip) the underlying issues appears to be  **Failed to connect to websocket**

### Expected Behavior

When launching steam from the created desktop icon that the landing page (Steam Store) be displayed.

### Steps To Reproduce

1. Click on Show Apps 
![image](https://github.com/canonical/steam-snap/assets/266067/105a792e-6f68-4240-8806-f33b01ba59ba)

2. Click on ![image](https://github.com/canonical/steam-snap/assets/266067/d8b277f5-8a2e-4cc1-987c-fdac28270122)

3. Observe that Steam store windows fails to be displayed.

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.04 LTS (Noble Numbat)"
snap_info:
    steam_revision:     191
    snapd_revision:     21759
lspci:
    08:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c4)
glxinfo:
    gpu:                AMD Radeon Graphics (radeonsi, renoir, LLVM 15.0.7, DRM 3.57, 6.8.0-31-generic)
    gpu_version:        4.6 (Core Profile) Mesa 24.0.3 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 9 5900HX with Radeon Graphics
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

**Comment by ashuntu** [comment] 2024-07-05 22:03
I was able to reproduce this, I'll keep this open so we can investigate.

**Comment by sergio-costas** [comment] 2024-07-30 09:34
I tried it in my system (with an AMD GPU) and everything seems to work as expected... I launch it from the snap store, from the gnome launcher or from the command line, and everything works. I don't have a shortcut in the desktop, anyway... I don't remember being asked to have it. How did you create it?

**Comment by sergio-costas** [comment] 2024-07-30 09:35
The shortcut in the desktop is a soft link, or is a fully-fledged .desktop file? If the former, can you tell me to what does it point? If the later, can you put here its contents? (open it with any text editor).

**Comment by jbsbbruno** [comment] 2024-08-01 02:30
> The shortcut in the desktop is a soft link, or is a fully-fledged .desktop file? If the former, can you tell me to what does it point? If the later, can you put here its contents? (open it with any text editor).

File .desktop. Shortcut created when installing the Steam .deb package.

**Comment by jbsbbruno** [comment] 2024-08-01 02:37
> I tried it in my system (with an AMD GPU) and everything seems to work as expected... I launch it from the snap store, from the gnome launcher or from the command line, and everything works. I don't have a shortcut in the desktop, anyway... I don't remember being asked to have it. How did you create it?

The Snap package also presented a problem, the game would not start. There are two problems, the program startup does not work in the Gnome Dock shortcut and the games do not start. Now I use Steam installed by the .deb package. It only works using the Steam.desktop shortcut or through the terminal command line. I'm using it like this and it's fine! I won't worry about this issue anymore.

**Comment by sergio-costas** [comment] 2024-08-01 10:27
Mmm... Do you have both .snap and .deb steams installed?

Also, it makes sense that the .desktop shortcut created by the .deb doesn't work...

**Comment by jhenstridge** [comment] 2024-08-13 09:17
The `console_log.txt` from your successful-launch.zip also includes the same "src/steamUI/webuitransportcontroller.cpp (206) : Failed to connect to websocket" message, so I suspect that's a red herring.

Out of interest, are the people seeing this problem running hybrid graphics/multi-GPU systems? The desktop file includes `PrefersNonDefaultGPU=true`, which would change how gnome-shell launches Steam compared to running it directly from the command line.

You can check if you have a hybrid graphics system by running `switcherooctl list` in a terminal, which will list multiple GPUs if this is the case. If this is the case, try right clicking on the Steam icon (either on the dock or app list) and choose "Launch using Integrated Graphics Card" to launch it. If that behaves any differently, it'd give some indication of where the problem resides.

**Comment by ashuntu** [comment] 2024-08-15 17:20
It seems like this behavior is identical to the Steam deb as well, which means it's likely not an issue with the Steam snap itself. You should be able to work around it in Ubuntu+GNOME by right-clicking the Steam shortcut and choosing "Launch with discrete GPU".

**Comment by vanvugt** [comment] 2024-08-16 07:50
> You should be able to work around it in Ubuntu+GNOME by right-clicking the Steam shortcut and choosing "Launch with discrete GPU".

That option shouldn't exist. Only "Launch using Integrated Graphics Card", because Discrete is already the default.

**Comment by ashuntu** [comment] 2024-08-16 15:02
Yes, the issue is noticeable since you can actually see the window trying to open, but it disappears quickly and causes focus to shift for a moment.

**Comment by ashuntu** [comment] 2024-08-19 15:00
Closing for now since this seems to be an issue with Steam, not just the snap version (in which case you should open an issue in https://github.com/ValveSoftware/steam-for-linux). If this isn't the case, feel free to reopen.

**Closed by ashuntu** 2024-08-19 15:00 UTC
Labels: type/bug, jira, keep-open
