### ISSUE TITLE
Steam snap wrong font.

### ISSUE THREAD

**Issue by amardhruva** [canonical/steam-snap#209] opened 2023-04-25 03:21 UTC
**Describe the bug**
Steam snap uses weird serif font.

**To Reproduce**
Fresh install of Kubuntu 23.04
Install steam snap
Launch and login.

**Expected behavior**
Proper font is used

**Screenshots**
![Screenshot_20230424_215055](https://user-images.githubusercontent.com/7582063/234166552-54106166-af83-4f46-8807-b29c2a24b366.png)

**Environment**
```
os_release: 
    name:               "Ubuntu"
    version:            "23.04 (Lunar Lobster)"
snap_info: 
    steam_revision:     136
    snapd_revision:     18933
lspci: 
    00:02.0:            Intel Corporation CometLake-H GT2 [UHD Graphics] (rev 05)
    01:00.0:            NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (rev a1)
glxinfo: 
    gpu:                Mesa Intel(R) UHD Graphics (CML GT2)
    gpu_version:        4.6 (Core Profile) Mesa 23.0.2 - kisak-mesa PPA
lscpu: 
    model_name:         Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
xdg_current_desktop:    KDE
desktop_session:        plasmawayland
```

**Logs**
```
flock /usr/share/fonts/truetype/freefont/FreeSerif.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerif.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerifBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerifBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSansBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSansBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSansBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSansBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerif.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerif.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSansBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSansBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerif.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerif.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerifBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerifBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerifBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerifBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/fonts-yrsa-rasa/Rasa-Medium.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/fonts-yrsa-rasa/Rasa-Medium.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerif.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerif.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/fonts-yrsa-rasa/Rasa-Medium.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/fonts-yrsa-rasa/Rasa-Medium.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSansBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSansBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerif.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerif.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerifBold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/freefont/FreeSerifBold.ttf LOCK_SH failed. errno = 13Installing breakpad exception handler for appid(steam)/version(1679680416)/tid(18119)
```

The font /usr/share/fonts/truetype/freefont/FreeSerif.ttf exists in the system.

**Comment by kenvandine** [comment] 2023-04-25 14:22
The warning about FreeSerif.ttf isn't actually the problem, but @ZoopOTheGoop is already working on a fix.

**Comment by ZoopOTheGoop** [comment] 2023-04-26 01:21
To be clear, you can work around this until it's fixed by installing `ttf-mscorefonts-installer` - sort of. It's complicated, but for various reasons font fallback on Lunar isn't working properly in Snaps at the moment. In older versions it would fall back to Liberation (which is not, but looks a heck of a lot like, Arial), but on Lunar in the Snap it incorrectly falls back to Free Serif. The actual fonts Steam requests are in `ttf-mscorefonts-installer` which is the *actual* correct font that Steam wants, but we cannot and will likely never distribute due to licensing issues (they're proprietary fonts, albeit cost-free to install on your end). 

No version of Ubuntu, or almost any GNU/Linux will by default produce the "correct" font without installing `ttf-mscorefonts-installer` (or else manually installing MS fonts like Arial), but we are producing a result significantly worse than the fallback option should be.

See this entry on the Arch Wiki for more info on Steam font stuff in general:
https://wiki.archlinux.org/title/Steam/Troubleshooting#Text_is_corrupt_or_missing

**Comment by amardhruva** [comment] 2023-04-27 05:21
I mean I don't think most people would care if the font displayed by steam is exactly Arial or not. But i think having a serif font looks out of place. Probably having it fall back to a sane font(Liberation?) would be the best solution.

**Comment by kurenedo** [comment] 2023-04-27 15:54
> ttf-mscorefonts-installer

I install fonts and it's work

**Comment by ZoopOTheGoop** [comment] 2023-04-27 16:14
> I mean I don't think most people would care if the font displayed by steam is exactly Arial or not. But i think having a serif font looks out of place. Probably having it fall back to a sane font(Liberation?) would be the best solution.

Yes, that's what we're trying to fix.

To give more context - the issue is that snap mounts `/etc/fonts/conf.d`, AKA the host fontconfig directory, but all the files in there are symlinks. Some got moved from `/etc/fonts/conf.avail` to ` /usr/share/fontconfig/conf.avail` in Lunar - unfortunately `snapd` isn't mounting that directory (and I'm working on figuring out exactly how to get it to do so right now). This was an issue at least as far back as Jammy it turns out, it just so happens that the files that weren't loaded properly by sheer coincidence didn't affect any of the fallback's Steam's fonts (like Arial) until now, so it went unnoticed. The ones that break Arial's fallback just so happened to be moved to a place that's inaccessible in Lunar, causing us to notice the problem for the first time.

So yeah, I'm working on the font fallback working by trying to mount the proper directory, until then, installing the actual fonts (to prevent fallback from occurring at all) will give you the proper fonts.

**Closed** 2023-05-02 14:09 UTC
Labels: bug
