### ISSUE TITLE
Black Screens. [SOLVED]

### ISSUE THREAD

**Issue by shithedark** [canonical/steam-snap#77] opened 2022-10-28 13:59 UTC
[Solved by system restart lol]

**Describe the bug**
Steam launches but with black screen, I am able to get to settings but not library etc.

**To Reproduce**
launch steam snap.

**Expected behavior**
No black screens.

**Screenshots**

**Environment**  

`snap info steam`  
name:      steam
summary:   Launcher for the Steam software distribution service (Early Access)
publisher: Canonical✓
store-url: https://snapcraft.io/steam
contact:   https://github.com/canonical/steam-snap
license:   unset
description: |
  Steam is a software distribution service with an online store, automated
  installation, automatic updates, achievements, SteamCloud synchronized
  savegame and screenshot functionality, and many social features.
commands:
  - steam.report
  - steam
snap-id:      NeoQngJVBf2wKC48bxnF2xqmfEFGdVnx
tracking:     latest/edge
refresh-date: 8 days ago, at 18:04 EEST
channels:
  latest/stable:    –                              
  latest/candidate: –                              
  latest/beta:      1.0.0.75 2022-10-07 (52) 365MB -
  latest/edge:      1.0.0.75 2022-10-19 (70) 378MB -
installed:          1.0.0.75            (70) 378MB -

`snap version`
snap    2.57.5+git885.g3c05e53
snapd   2.57.5+git885.g3c05e53
series  16
ubuntu  22.10
kernel  5.19.0-23-generic

Distro & version:  Ubuntu 22.10
CPU:  Intel® Core™ i7-8550U × 8
GPU:  Mesa Intel® UHD Graphics 620 (KBL GT2)
GPU Driver Version:  Default Intel Driver.

**Additional context**
Yesterday it was working perfectly !

**Comment by ashuntu** [comment] 2022-10-28 15:21
Closing as the issue is resolved.

**Closed by ashuntu** 2022-10-28 15:21 UTC
Labels: bug
